spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/caidonglun/spring-cloud-config-server-test.git
#          username: 
#          password: 

server:
  port: 8056

#配置security的账号密码
security:
  basic:
    enabled: true
  user:
    name: user
    password: user



#encrypt:
#  key: foo