spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/caidonglun/spring-cloud-config-server-test.git

server:
  port: 8052
#rabbitmq的服务器
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

#encrypt:
#  key: foo